tap "buildpacks/tap"
tap "depot/tap"
tap "homebrew/bundle"
tap "libsql/sqld"
tap "lightbend/brew"
tap "oven-sh/bun"
tap "stripe/stripe-cli"
tap "surrealdb/tap"
tap "tursodatabase/tap"
brew "zstd"
brew "webp"
brew "libssh2"
brew "bat"
brew "unbound"
brew "colima"
brew "dasel"
brew "docker"
brew "docker-buildx"
brew "fd"
brew "ffmpeg"
brew "node"
brew "firebase-cli"
brew "fswatch"
brew "fzf"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "go"
brew "gource"
brew "gradle"
brew "graphviz"
brew "grpcurl"
brew "hadolint"
brew "htop"
brew "hyperfine"
brew "libheif"
brew "imagemagick"
brew "jenv"
brew "jpegoptim"
brew "jq"
brew "openjdk@11"
brew "ki"
brew "kotlin"
brew "lsusb"
brew "mas"
brew "maven"
brew "mozjpeg"
brew "ncdu"
brew "openjdk@17"
brew "openssl@1.1"
brew "parallel"
brew "pipx"
brew "pnpm"
brew "pre-commit"
brew "python@3.10"
brew "python@3.11"
brew "redis"
brew "rename"
brew "ruby"
brew "rust"
brew "rustup-init"
brew "terraform"
brew "terraformer"
brew "tree"
brew "vercel-cli"
brew "virtualenv"
brew "wget"
brew "zip"
brew "buildpacks/tap/pack"
brew "depot/tap/depot"
brew "lightbend/brew/kalix"
brew "oven-sh/bun/bun"
brew "stripe/stripe-cli/stripe"
brew "surrealdb/tap/surreal"
brew "tursodatabase/tap/turso"
cask "android-commandlinetools"
cask "android-platform-tools"
cask "anydesk"
cask "betterdiscord-installer"
cask "chrome-remote-desktop-host"
cask "deepl"
cask "discord"
cask "firefox"
cask "ghidra"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "intellij-idea"
cask "iterm2"
cask "jetbrains-toolbox"
cask "macfuse"
cask "macpass"
cask "multimc"
cask "notion"
cask "obs"
cask "obs-virtualcam"
cask "obsidian"
cask "openaudible"
cask "postman"
cask "raycast"
cask "responsively"
cask "signal"
cask "sublime-text"
cask "timing"
cask "tor-browser"
cask "warp"
cask "whatsapp"
mas "Amphetamine", id: 937984704
mas "AusweisApp", id: 948660805
mas "Boop", id: 1518425043
mas "Color Picker", id: 1545870783
mas "Day Progress", id: 6450280202
mas "io.bgoerke.photo-anonymizator", id: 1624700848
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Outbank", id: 1094255754
mas "Pages", id: 409201541
mas "Parallels Desktop", id: 1085114709
mas "Pastebot", id: 1179623856
mas "Quick Camera", id: 598853070
mas "Scaler", id: 1612708557
mas "Sticky Notes", id: 1150887374
mas "TripMode", id: 1513400665
