# treefmt configuration for Setup-Mac project
# Universal code formatter configuration
# Comprehensive formatting for multiple languages

[formatter.go]
command = "gofumpt"
options = ["-w"]
includes = ["*.go"]

# Disabled temporarily until formatters are installed via Nix
# [formatter.javascript]
# command = "prettier"
# options = [
#     "--write",
#     "--tab-width", "2",
#     "--single-quote",
#     "--trailing-comma", "es5",
#     "--print-width", "100",
#     "--semi",
#     "--bracket-spacing",
#     "--arrow-parens", "avoid"
# ]
# includes = [
#     "*.js", "*.ts", "*.jsx", "*.tsx",
#     "*.json", "*.yaml", "*.yml", "*.md",
#     "*.css", "*.scss", "*.html"
# ]

# [formatter.nix]
# command = "nixfmt"
# options = ["--width", "100"]
# includes = ["*.nix"]

# [formatter.shell]
# command = "shfmt"
# options = ["-w", "-i", "2", "-ci", "-s"]
# includes = ["*.sh", "*.bash"]

# Global settings and exclusions
[global]
excludes = [
    # Lock files and dependencies
    "*.lock",
    "package-lock.json",
    "yarn.lock", 
    "pnpm-lock.yaml",
    "Cargo.lock",
    "poetry.lock",
    
    # Build artifacts and dependencies
    "node_modules/",
    ".next/",
    "dist/",
    "build/",
    "target/",
    "vendor/",
    ".cache/",
    
    # Version control and environment
    ".git/",
    ".direnv/",
    ".env*",
    
    # Nix build results
    "result",
    "result-*",
    
    # Backups and temporary files
    "backups/",
    "*.tmp",
    "*.bak", 
    "*.backup",
    
    # Log files
    "*.log",
    
    # IDE and editor files
    ".vscode/",
    ".idea/",
    "*.swp",
    "*.swo",
    "*~",
    
    # macOS system files
    ".DS_Store",
    "._*"
]