name: Go tests

on:
  push:
    branches: [master]
    paths:
      - "pkgs/dnsblockd-processor/**"
  pull_request:
    branches: [master]
    paths:
      - "pkgs/dnsblockd-processor/**"

jobs:
  dnsblockd-processor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/dnsblockd-processor
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: pkgs/dnsblockd-processor/go.mod

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...
